name: to_do_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  date_picker_timeline: null
  flutter:
    sdk: flutter
  flutter_launcher_icons: null
  flutter_local_notifications: null
  flutter_staggered_animations: null
  flutter_timezone: null
  get_storage: null
  google_fonts: null
  intl: null
  provider: ^6.0.5
  rxdart: null
  sqflite: null
  timezone: null

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/to_do_app_icon.png"

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets\circle_avatar.png
